version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: triconnect
      MYSQL_DATABASE: triconnect
    ports:
      - '3306:3306'
    command: --max_connections=1000 --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
